# Generated by Django 5.2.8 on 2025-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_product_options_product_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
