# Generated by Django 5.2.8 on 2025-11-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_product_body_condition_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
